//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReader
    {
        public long id { get; set; }
        public Nullable<long> book_id { get; set; }
        public Nullable<long> reader_id { get; set; }
        public Nullable<System.DateTime> borrow_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public string status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
